/*
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 */

/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 21:07:49 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.GnuParser;
import org.apache.commons.cli.Options;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GnuParser_ESTest extends GnuParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Options options0 = new Options();
      String[] stringArray0 = new String[14];
      options0.addOption("b", "b");
      stringArray0[1] = "-bsW=";
      GnuParser gnuParser0 = new GnuParser();
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, true);
      Options options1 = new Options();
      String[] stringArray2 = gnuParser0.flatten(options1, stringArray1, true);
      assertEquals(2, stringArray2.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Options options0 = new Options();
      String[] stringArray0 = new String[14];
      Options options1 = options0.addOption("b", "b");
      stringArray0[1] = "-bsW=";
      GnuParser gnuParser0 = new GnuParser();
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, true);
      String[] stringArray2 = gnuParser0.flatten(options1, stringArray1, true);
      assertEquals(2, stringArray2.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Options options0 = new Options();
      String[] stringArray0 = new String[14];
      stringArray0[5] = "-";
      GnuParser gnuParser0 = new GnuParser();
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, true);
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[14];
      stringArray0[2] = "--";
      GnuParser gnuParser0 = new GnuParser();
      Options options0 = new Options();
      CommandLine commandLine0 = gnuParser0.parse(options0, stringArray0);
      assertNotNull(commandLine0);
  }
}
